# -*- mode: ruby -*-
# vi: set ft=ruby :

# Modify these variables if needed
VM_IP = "192.168.56.9"
BACKEND_VM_PATH = "/repositories/lu.uni.e4l.platform.api.dev"
FRONTEND_VM_PATH = "/repositories/lu.uni.e4l.platform.frontend.dev"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "devops-exam"
  
  ENV['LC_ALL']="en_US.UTF-8"

  config.vm.network "forwarded_port", guest: 8088, host: 8080

  # Modify the host ports if they are already in use on your machine
  config.vm.network "forwarded_port", guest: 8084, host: 8084 # Backend Staging
  config.vm.network "forwarded_port", guest: 8085, host: 8085 # Backend Production (Blue)
  config.vm.network "forwarded_port", guest: 8086, host: 8086 # Backend Production (Green)
  config.vm.network "forwarded_port", guest: 8090, host: 8090 # Backend Released (Nginx - either Blue or Green)
  
  config.vm.network "forwarded_port", guest: 8884, host: 8884 # Frontend Staging
  config.vm.network "forwarded_port", guest: 8885, host: 8885 # Frontend Production (Blue)
  config.vm.network "forwarded_port", guest: 8886, host: 8886 # Frontend Production (Green)
  config.vm.network "forwarded_port", guest: 8890, host: 8890 # Frontend Released (Nginx - either Blue or Green)

  # Mount local project directories
  config.vm.synced_folder "../lu.uni.e4l.platform.api.dev", BACKEND_VM_PATH
  config.vm.synced_folder "../lu.uni.e4l.platform.frontend.dev", FRONTEND_VM_PATH

  config.vm.network "private_network", ip: VM_IP

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 8 * 1024
    vb.cpus = 4
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
   	SHELL

  config.vm.provision "primary_ansible", type: "ansible" do |ansible|
    ansible.playbook = "./playbook/primary.yml"
    ansible.ask_vault_pass = true
    ansible.extra_vars = {
      gitlab_domain: VM_IP,
      backend_VM_path: BACKEND_VM_PATH,
      frontend_VM_path: FRONTEND_VM_PATH
    }
  end

  # config.vm.provision "secondary_ansible", type: "ansible", run: "never" do |ansible|
  #   ansible.playbook = "./playbook/secondary.yml"
  #   ansible.extra_vars = {
  #     gitlab_domain: VM_IP
  #   }
  # end
   
end